import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

/* carrega todos os pesos necessários e expõe a CSS var --font-mont */
const mont = localFont({
  variable: '--font-mont',
  display: 'swap',
  src: [
    { path: '../../public/fonts/Mont-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../../public/fonts/Mont-Bold.woff2', weight: '700', style: 'normal' },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt" className={mont.variable}>
      {/* a var é registrada aqui; Tailwind resolve font-sans/mono via @theme */}
      <body className="antialiased">{children}</body>
    </html>
  )
}
